### ISSUE TITLE
Download failed

### ISSUE THREAD

**Issue by alxhoff** [munober/webscrapper#13]
**Describe the bug**
Image downloading failed

**Screenshots**
```
Traceback (most recent call last):

  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f19b9dce430>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./scrapper.py", line 627, in <module>
    start_search(google=True, imdb=True, manual=args.manual, list=args.list,
  File "./scrapper.py", line 396, in start_search
    run_search(manual, "both", headless_switch, ss_sameple_size)
  File "./scrapper.py", line 349, in run_search
    search_and_download(
  File "./scrapper.py", line 333, in search_and_download
    res_google = fetch_image_urls_google(
  File "/home/alxhoff/git/GitHub/webscrapper/google_link_collector.py", line 17, in fetch_image_urls_google
    wd.get(search_url.format(q=query))
  File "/usr/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.8/site-packages/urllib3/request.py", line 79, in request
    return self.request_encode_body(
  File "/usr/lib/python3.8/site-packages/urllib3/request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3.8/site-packages/urllib3/poolmanager.py", line 336, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 752, in urlopen
    return self.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 752, in urlopen
    return self.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 752, in urlopen
    return self.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=59051): Max retries exceeded with url: /session/6bb4c772-c000-413b-94da-a9bce7e0783b/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f19b9dce430>: Failed to establish a new connection: [Errno 111] Connection refused'))

```

**Comment by munober** [comment]
not sure why this happens - I'm not getting this error, but will look into it. Just off the top of my head, I've only used python 3.7 for the whole project and you seem to have 3.8 - not that it would make any difference and I tested it on 3.8 on Manjaro a while back with no issues.

**Comment by alxhoff** [comment]
I would just punch it into google and see what comes up

**Comment by munober** [comment]
Ok so I couldn't reproduce this, but I read about the error codes and the first one seems to be related to the socket library that selenium uses, namely that a tcp connection fails. The second one seems similar and related to IP addresses or ports. What I think is weird is the very last line where it seems to want to connect to localhost, and I can't understand why it wants to do that. Do you know what this could be about? What did you run to get this error? Did it come up repeatedly? Were you in headless mode?

**Comment by alxhoff** [comment]
Yer I am not sure about the localhost thing. I will try to recreate it and go into it a bit deeper to see what's going on

**Comment by munober** [comment]
ok so I finally got this too ayy - but only when running headless chrome

**Comment by alxhoff** [comment]
weird. I'm a firefox guy :P
